/*
 *  Copyright 2012 Intel Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var _timezone_data = {
    "UTC": {diff: 0, abbr: "UTC"},
    "Africa/Cairo": {diff: 2, abbr: "EET"},
    "Africa/Casablanca": {diff: 0, abbr: "UTC"},
    "Africa/Dakar": {diff: 0, abbr: "UTC"},
    "Africa/Freetown": {diff: 0, abbr: "UTC"},
    "Africa/Johannesburg": {diff: 2, abbr: "SAST"},
    "Africa/Luanda": {diff: 1, abbr: "WAT"},
    "America/Anchorage": {diff: -9, abbr: "AKDT"},
    "America/Antigua": {diff: -4, abbr: "AST"},
    "America/Aruba": {diff: -4, abbr: "AST"},
    "America/Barbados": {diff: -4, abbr: "AST"},
    "America/Belize": {diff: -6, abbr: "CST"},
    "America/Bogota": {diff: -5, abbr: "COT"},
    "America/Buenos_Aires": {diff: -3, abbr: "ART"},
    "America/Cancun": {diff: -6, abbr: "CDT"},
    "America/Cayenne": {diff: -3, abbr: "GFT"},
    "America/Cayman": {diff: -5, abbr: "EST"},
    "America/Chicago": {diff: -6, abbr: "CST"},
    "America/Chihuahua": {diff: -7, abbr: "MST"},
    "America/Costa_Rica": {diff: -6, abbr: "CST"},
    "America/Denver": {diff: -7, abbr: "MST"},
    "America/Detroit": {diff: -5, abbr: "EST"},
    "America/Dominica": {diff: -4, abbr: "AST"},
    "America/Edmonton": {diff: -7, abbr: "MST"},
    "America/El_Salvador": {diff: -6, abbr: "CST"},
    "America/Guatemala": {diff: -6, abbr: "CST"},
    "America/Havana": {diff: -5, abbr: "CST"},
    "America/Indianapolis": {diff: -5, abbr: "EST"},
    "America/Jamaica": {diff: -5, abbr: "EST"},
    "America/Lima": {diff: -5, abbr: "PET"},
    "America/Los_Angeles": {diff: -8, abbr: "PST"},
    "America/Louisville": {diff: -5, abbr: "EST"},
    "America/Mexico_City": {diff: -6, abbr: "CST"},
    "America/Montevideo": {diff: -2, abbr: "UYST"},
    "America/Montreal": {diff: -5, abbr: "EST"},
    "America/New_York": {diff: -5, abbr: "EST"},
    "America/Panama": {diff: -5, abbr: "EST"},
    "America/Phoenix": {diff: -7, abbr: "MST"},
    "America/Puerto_Rico": {diff: -4, abbr: "AST"},
    "America/Santiago": {diff: -3, abbr: "CLST"},
    "America/Santo_Domingo": {diff: -4, abbr: "AST"},
    "America/Sao_Paulo": {diff: -4, abbr: "AST"},
    "America/Tijuana": {diff: -8, abbr: "PST"},
    "America/Vancouver": {diff: -8, abbr: "PST"},
    "America/Winnipeg": {diff: -6, abbr: "CST"},
    "Antarctica/South_Pole": {diff: 13, abbr: "NZDT"},
    "Arctic/Longyearbyen": {diff: 13, abbr: "CET"},
    "Asia/Amman": {diff: 2, abbr: "EET"},
    "Asia/Baghdad": {diff: 3, abbr: "AST"},
    "Asia/Bahrain": {diff: 3, abbr: "AST"},
    "Asia/Bangkok": {diff: 7, abbr: "ICT"},
    "Asia/Beirut": {diff: 2, abbr: "EET"},
    "Asia/Chungking": {diff: 8, abbr: "CST"},
    "Asia/Dubai": {diff: 4, abbr: "GST"},
    "Asia/Harbin": {diff: 8, abbr: "CST"},
    "Asia/Ho_Chi_Minh": {diff: 7, abbr: "IST"},
    "Asia/Hong_Kong": {diff: 8, abbr: "HKT"},
    "Asia/Istanbul": {diff: 2, abbr: "EET"},
    "Asia/Jakarta": {diff: 7, abbr: "WIT"},
    "Asia/Jerusalem": {diff: 2, abbr: "IST"},
    "Asia/Karachi": {diff: 5, abbr: "PKT"},
    "Asia/Kuala_Lumpur": {diff: 8, abbr: "MYT"},
    "Asia/Kuwait": {diff: 3, abbr: "AST"},
    "Asia/Macao": {diff: 8, abbr: "CST"},
    "Asia/Manila": {diff: 8, abbr: "PHT"},
    "Asia/Pyongyang": {diff: 9, abbr: "KST"},
    "Asia/Qatar": {diff: 3, abbr: "AST"},
    "Asia/Saigon": {diff: 7, abbr: "ICT"},
    "Asia/Seoul": {diff: 9, abbr: "KST"},
    "Asia/Shanghai": {diff: 8, abbr: "CST"},
    "Asia/Singapore": {diff: 8, abbr: "SGT"},
    "Asia/Taipei": {diff: 8, abbr: "CST"},
    "Asia/Tel_Aviv": {diff: 2, abbr: "IST"},
    "Asia/Tokyo": {diff: 9, abbr: "JST"},
    "Asia/Urumqi": {diff: 8, abbr: "CST"},
    "Atlantic/Bermuda": {diff: -4, abbr: "AST"},
    "Atlantic/Canary": {diff: 0, abbr: "WET"},
    "Atlantic/Cape_Verde": {diff: -1, abbr: "CVT"},
    "Atlantic/Reykjavik": {diff: 0, abbr: "GMT"},
    "Australia/Brisbane": {diff: 10, abbr: "EST"},
    "Australia/Canberra": {diff: 11, abbr: "EST"},
    "Australia/Darwin": {diff: 9.5, abbr: "CST"},
    "Australia/Melbourne": {diff: 11, abbr: "EST"},
    "Australia/North": {diff: 9.5, abbr: "CST"},
    "Australia/Perth": {diff: 8, abbr: "WST"},
    "Australia/Queensland": {diff: 10, abbr: "EST"},
    "Australia/South": {diff: 10.5, abbr: "CST"},
    "Australia/Sydney": {diff: 11, abbr: "EST"},
    "Australia/West": {diff: 8, abbr: "WST"},
    "Australia/Victoria": {diff: 11, abbr: "EST"},
    "Europe/Amsterdam": {diff: 1, abbr: "CET"},
    "Europe/Athens": {diff: 2, abbr: "EET"},
    "Europe/Belgrade": {diff: 1, abbr: "CET"},
    "Europe/Berlin": {diff: 1, abbr: "CET"},
    "Europe/Brussels": {diff: 1, abbr: "CET"},
    "Europe/Bucharest": {diff: 2, abbr: "EET"},
    "Europe/Budapest": {diff: 1, abbr: "CET"},
    "Europe/Copenhagen": {diff: 1, abbr: "CET"},
    "Europe/Dublin": {diff: 0, abbr: "GMT"},
    "Europe/Helsinki": {diff: 2, abbr: "EET"},
    "Europe/Istanbul": {diff: 2, abbr: "EET"},
    "Europe/Kaliningrad": {diff: 3, abbr: "FET"},
    "Europe/Kiev": {diff: 2, abbr: "EET"},
    "Europe/Lisbon": {diff: 0, abbr: "WET"},
    "Europe/London": {diff: 0, abbr: "GMT"},
    "Europe/Luxembourg": {diff: 1, abbr: "CET"},
    "Europe/Madrid": {diff: 1, abbr: "CET"},
    "Europe/Minsk": {diff: 3, abbr: "FET"},
    "Europe/Monaco": {diff: 1, abbr: "CET"},
    "Europe/Moscow": {diff: 4, abbr: "MSK"},
    "Europe/Oslo": {diff: 1, abbr: "CET"},
    "Europe/Paris": {diff: 1, abbr: "CET"},
    "Europe/Prague": {diff: 1, abbr: "CET"},
    "Europe/Rome": {diff: 1, abbr: "CET"},
    "Europe/San_Marino": {diff: 1, abbr: "CET"},
    "Europe/Sarajevo": {diff: 1, abbr: "CET"},
    "Europe/Stockholm": {diff: 1, abbr: "CET"},
    "Europe/Vatican": {diff: 1, abbr: "CET"},
    "Europe/Vienna": {diff: 1, abbr: "CET"},
    "Europe/Warsaw": {diff: 1, abbr: "CET"},
    "Europe/Zurich": {diff: 2, abbr: "EET"},
    "Indian/Christmas": {diff: 7, abbr: "CXT"},
    "Indian/Maldives": {diff: 5, abbr: "MVT"},
    "Pacific/Auckland": {diff: 12, abbr: "NZST"},
    "Pacific/Easter": {diff: -6, abbr: "EAST"},
    "Pacific/Fiji": {diff: 12, abbr: "FJT"},
    "Pacific/Guam": {diff: 10, abbr: "ChST"},
    "Pacific/Honolulu": {diff: -10, abbr: "HST"},
    "Pacific/Midway": {diff: -11, abbr: "SST"},
    "Pacific/Saipan": {diff: 10, abbr: "ChST"},
    "Pacific/Samoa": {diff: -11, abbr: "SST"},
    "Pacific/Tahiti": {diff: -10, abbr: "TAHT"},
    "UCT": {diff: 0, abbr: "UCT"},
    "SST": {diff: 0, abbr: "SST"},
    "GMT": {diff: 0, abbr: "GMT"},
    "Greenwich": {diff: 0, abbr: "GMT"},
    "US/Alaska": {diff: -9, abbr: "AKST"},
    "US/Eastern": {diff: -5, abbr: "EST"},
    "US/Central": {diff: -6, abbr: "CST"},
    "US/Mountain": {diff: -7, abbr: "MST"},
    "US/Pacific": {diff: -8, abbr: "PST"},
    "Universal": {diff: 0, abbr: "UTC"},
    "Zulu": {diff: 0, abbr: "UTC"},
    "Etc/GMT": {diff: 0, abbr: "Etc/GMT"},
    "Etc/GMT+0": {diff: 0, abbr: "Etc/GMT+0"},
    "Etc/GMT+1": {diff: -1, abbr: "Etc/GMT+1"},
    "Etc/GMT+10": {diff: -10, abbr: "Etc/GMT+10"},
    "Etc/GMT+11": {diff: -11, abbr: "Etc/GMT+11"},
    "Etc/GMT+12": {diff: -12, abbr: "Etc/GMT+12"},
    "Etc/GMT+2": {diff: -2, abbr: "Etc/GMT+2"},
    "Etc/GMT+3": {diff: -3, abbr: "Etc/GMT+3"},
    "Etc/GMT+4": {diff: -4, abbr: "Etc/GMT+4"},
    "Etc/GMT+5": {diff: -5, abbr: "Etc/GMT+5"},
    "Etc/GMT+6": {diff: -6, abbr: "Etc/GMT+6"},
    "Etc/GMT+7": {diff: -7, abbr: "Etc/GMT+7"},
    "Etc/GMT+8": {diff: -8, abbr: "Etc/GMT+8"},
    "Etc/GMT+9": {diff: -9, abbr: "Etc/GMT+9"},
    "Etc/GMT-0": {diff: 0, abbr: "Etc/GMT-0"},
    "Etc/GMT-1": {diff: 1, abbr: "Etc/GMT-1"},
    "Etc/GMT-10": {diff: 10, abbr: "Etc/GMT-10"},
    "Etc/GMT-11": {diff: 11, abbr: "Etc/GMT-11"},
    "Etc/GMT-12": {diff: 12, abbr: "Etc/GMT-12"},
    "Etc/GMT-13": {diff: 13, abbr: "Etc/GMT-13"},
    "Etc/GMT-14": {diff: 14, abbr: "Etc/GMT-14"},
    "Etc/GMT-2": {diff: 2, abbr: "Etc/GMT-2"},
    "Etc/GMT-3": {diff: 3, abbr: "Etc/GMT-3"},
    "Etc/GMT-4": {diff: 4, abbr: "Etc/GMT-4"},
    "Etc/GMT-5": {diff: 5, abbr: "Etc/GMT-5"},
    "Etc/GMT-6": {diff: 6, abbr: "Etc/GMT-6"},
    "Etc/GMT-7": {diff: 7, abbr: "Etc/GMT-7"},
    "Etc/GMT-8": {diff: 8, abbr: "Etc/GMT-8"},
    "Etc/GMT-9": {diff: 9, abbr: "Etc/GMT-9"},
    "Etc/GMT0": {diff: 0, abbr: "Etc/GMT0"},
    "Etc/Greenwich": {diff: 0, abbr: "GMT"}
};

module.exports = {
    getAllTimezone: function () {
        var i, ret = [];
        for (i in _timezone_data)
            ret.push(i);
        return ret;
    },
    getTimezoneDiff: function (zone) {
        return _timezone_data[zone].diff;
    },
    getTimezoneAbbr: function (zone) {
        return _timezone_data[zone].abbr;
    },
    isValidTimezone: function (zone) {
        return (_timezone_data[zone] === undefined) ? false : true;
    }
};

